### ISSUE TITLE
simplify apigeecli installation

### ISSUE THREAD

**Issue by danistrebel** [GoogleCloudPlatform/apigee-anthos-service-mesh-demo#5]
there's a convenience function to install the latest version: https://github.com/apigee/apigeecli/blob/master/downloadLatest.sh

**Comment by ssvaidyanathan** [comment]
@danistrebel - so the ask is to use this instead within the apigee scripts?

**Comment by danistrebel** [comment]
yeah a proposal would be to replace https://github.com/GoogleCloudPlatform/apigee-anthos-service-mesh-demo/blob/main/deploy-apigee.sh#L68-L72 with a callout to this script. Would make it easier to support different OS versions as well.
