### ISSUE TITLE
deploy-wait is deprecated 

### ISSUE THREAD

**Issue by ganadurai** [GoogleCloudPlatform/apigee-anthos-service-mesh-demo#8]
https://github.com/apigee/apigeecli/commit/afc64fdd50e37e2778b8ae919f1558400844c6c2

deploy-wait is deprecated in version v1.111. The code in deploy-apigee.sh need a fix.

**Comment by ssvaidyanathan** [comment]
Its been fixed. Please try it out and reopen if the issue still persists
